# Generated by Django 3.2.5 on 2022-09-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProuctIndusty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Products Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductSemiIndusry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='industry.prouctindusty', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product Sub-Category',
                'verbose_name_plural': 'Products Sub-Categories',
            },
        ),
    ]
